### ISSUE TITLE
Optionally display private messages

### ISSUE THREAD

**Issue by Gantonator** [zoetrope69/ko-fi-xyz#28]
https://github.com/zaccolley/ko-fi-alerts/blob/af236abec8f160a24609ae8e84166944553a7921/pages/api/webhook/%5Bid%5D.js#L65

I might be completely wrong and maybe you have already done this somewhere else.  The popout for OBS could/should display private messages to the streamer, as the intention isn't to make it visible to the stream but only to the streamer.

Should be clear if they are private though.

Again sorry if this is done already and I am pig brained 🙏

**Comment by zaccolley** [comment]
You're right, private messages should probably only be hidden in the alerts but showing on the dashboard (in OBS). This is deffo a bug.
